### ISSUE TITLE
question(service-worker): what percentage of mobile browsers support either SW or AppCache?

### ISSUE THREAD

**Issue by jeffbcross** [angular/offline#7]
From the [design doc](https://github.com/angular/offline/blob/master/service-worker/design/index.md): 

> but there are other mobile browsers that have high usage in specific markets which also don't support the API.

Is there data available to indicate what percentage of market will be supported by supporting both AppCache and SW?

**Comment by robwormald** [comment]
http://caniuse.com/#feat=offline-apps 
http://caniuse.com/#feat=serviceworkers

pretty decent coverage

**Comment by jeffbcross** [comment]
According to their stats, Opera Mini is the largest holdout at 4.79% of global marketshare. Overall, looks like 91.8% of users can benefit from the design.
